package com.myspace.miproyecto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Jewelry implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String offer;
	private java.lang.String type;

	public Jewelry() {
	}

	public java.lang.String getOffer() {
		return this.offer;
	}

	public void setOffer(java.lang.String offer) {
		this.offer = offer;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public Jewelry(java.lang.String offer, java.lang.String type) {
		this.offer = offer;
		this.type = type;
	}

}